[package]
name = "converted_assume_true"
version = "0.1.0"
authors = ["np <nataliepopescu@gmail.com>"]
edition = "2018"

[[bin]]
name = "test_bc"
path = "bin/test_bc.rs"

[dependencies]
rand = "*"
forpaper = { path = "/home/npopescu/hack/assume_true/forpaper/" }
