[package]
name = "converted_fancy-regex"
version = "0.1.0"
authors = ["np <nataliepopescu@gmail.com>"]
edition = "2018"

[[bin]]
name = "test_bc"
path = "bin/test_bc.rs"

[dependencies]
fancy-regex = "0.4.1"
regex = "1.2"
