[package]
name = "converted_impl-serde"
version = "0.1.0"
authors = ["np <nataliepopescu@gmail.com>"]
edition = "2018"

[[bin]]
name = "test_bc"
path = "bin/test_bc.rs"

[dependencies]
impl-serde = "0.3.1"
serde_json = "1.0.41"
uint = "0.8.3"
