[package]
name = "converted_bytecount"
version = "0.1.0"
authors = ["np <nataliepopescu@gmail.com>"]
edition = "2018"

[[bin]]
name = "test_bc"
path = "bin/test_bc.rs"

[dependencies]
bytecount = "0.6.2"
rand = "0.7"
