[package]
name = "converted_tracing-subscriber"
version = "0.1.0"
authors = ["np <nataliepopescu@gmail.com>"]
edition = "2018"

[[bin]]
name = "test_bc"
path = "bin/test_bc.rs"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2.15"
criterion = "0.3.0"
