[package]
name = "converted_rdrand"
version = "0.1.0"
authors = ["np <nataliepopescu@gmail.com>"]
edition = "2018"

[[bin]]
name = "test_bc"
path = "bin/test_bc.rs"

[dependencies]
rdrand = "0.7.0"
rand_core = "0.5.1"
